export function getRandomLoadingText() {
  const loadingTexts = [
    "Hold my coffee ☕",
    "Spilling the tea real quick ☕",
    "Feeding the server hamsters 🐹⚙️",
    "Overclocking my last two brain cells 🧠⚡",
    "Teaching the code to behave 🤫",
    "Putting on my wizard hat 🧙‍♂️",
    "Loading maximum chaos 100% 💥",
    "One moment, sacrificing a GPU to the AI gods 🔥",
    "Hold tight, untangling the spaghetti code 🍝",
    "Brewing something dangerously clever ☕🧪",
    "Waking up the neurons... again 😴→⚡",
    "Sharpening my digital claws 🐯",
    "Summoning the answer from the void 🌌",
    "Just a sec, bribing the electrons 💸",
    "Loading sarcasm levels: lethal 😈",
    "Doing a quick backflip, brb 🤸",
    "Convincing the bits to line up nicely 🔢",
    "Hold my energy drink, this might take 0.3s 🥤",
    "Polishing the snark cannons ✨",
    "Reticulating splines... (classic) 📈",
    "Injecting pure wit straight into the mainframe 💉",
    "Give me two shakes of a lamb’s tail 🐑",
    "Microwaving the answer ⚡🍲",
    "Unleashing the kraken of knowledge 🐙📚",
    "Rolling for initiative 🎲",
    "Charging sass reserves 47% → 100% 😏",
    "Tell the loading bar to hurry up ⏳🤜",
    "Consulting the magic 8-ball 🎱",
    "Defrosting my best comeback ❄️→🔥",
    "Turning coffee into code again ☕→💻",
    "Hold up, moonwalking to the database 🌙",
    "Adding extra spice 🌶️",
    "Booting up the roasts 🔥",
    "Patience, young padawan 🧘‍♂️",
    "Flipping the hourglass... dramatically ⌛",
    "Downloading extra funny from the cloud ☁️😂",
    "Cranking the meme generator to 11 🎰",
    "Almost there, don’t blink 👀",
    "Doing science to it 🧪⚗️",
    "Buffering epic response... 📶",
    "Hold my avocado toast 🥑",
    "Threatening the server with a wet noodle 🍜😈",
    "Loading puns, please wait... you’ll groan 📜",
    "Engaging maximum overthink 🤯",
    "Just vibing with the ones and zeros 1010🎶",
    "Be right back, high-fiving a quantum particle ✋⚛️",
    "Sprinkling extra Grok sauce 🟢",
    "Reticulating awesomeness... 98% ✨",
    "One more second... okay maybe three ⏱️",
    "Hold my beer, watch this 🍺🚀",
  ]

  return loadingTexts[Math.floor(Math.random() * loadingTexts.length)]
}
